Resources:
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      WebsiteConfiguration:
        IndexDocument: 'index.html'

  WebsiteBucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties: 
      Bucket: { Ref: WebsiteBucket }
      PolicyDocument:
        Statement: 
        - 
          Action: 
            - "s3:GetObject"
          Effect: "Allow"
          Resource: 
            Fn::Join:
              - ''
              - - 'arn:aws:s3:::'
                - { Ref: WebsiteBucket }
                - '/*'
          Principal: "*"

  WebAppCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName:
              Fn::Join:
                - ''
                - - Ref: WebsiteBucket
                  - .s3 # This needs to be changed to additional string if using outside of us-east-1: s3-${self:provider.region} or if using a non SPA type site, use the s3 website url: s3-website-${self:provider.region}
                  - .amazonaws.com
            Id: WebApp
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
        Enabled: 'true'
        Aliases: ${self:custom.system.cloudfront.aliases.${opt:stage, 'dev'}}
        HttpVersion: http2
        ViewerCertificate: ${self:custom.system.cloudfront.certificates.${opt:stage, 'dev'}}
        DefaultRootObject: index.html
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
        DefaultCacheBehavior:
          Compress: true
          AllowedMethods:
            - DELETE
            - GET
            - HEAD
            - OPTIONS
            - PATCH
            - POST
            - PUT
          TargetOriginId: WebApp
          ForwardedValues:
            QueryString: 'false'
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
Outputs:
  s3Websitebucket:
    Description: 'The bucket name for the s3 website.'
    Value:
      Ref: WebsiteBucket

  s3WebsitebucketUrl:
    Description: 'The url for the s3 website'
    Value:
      Fn::GetAtt: [ WebsiteBucket, WebsiteURL ]

  WebAppCloudFrontDistributionOutput:
    Value:
      Fn::GetAtt: [ WebAppCloudFrontDistribution, DomainName ]